[package]
name = "key_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hex = "0.4"
hex-literal = "0.4.1"
lambdaworks-math = "=0.5.0"
num-bigint = "0.4.4"